import { Specialty, Doctor } from '../../../services/api/types';
import firestore from '@react-native-firebase/firestore';

const list: Doctor[] = [
  {
    id: '1',
    avatar: 'https://images2.imgbox.com/f7/bb/7HJeSokt_o.png',
    title: Specialty.NEUROLOGY,
    name: '',
    specialty: [Specialty.NEUROLOGY],
    bio: '',
    email: '',
    address: '',
    phone: '',
    availability: [0, 1, 2],
    appointments: [
      {
        date: firestore.Timestamp.fromDate(new Date(2021, 10, 61)),
        userId: 'user id 1',
      },
    ],
  },
  {
    id: '2',
    avatar: 'https://images2.imgbox.com/5d/c9/sqb7cQMS_o.png',
    title: Specialty.DERMATOLOGY,
    name: '',
    specialty: [Specialty.NEUROLOGY],
    bio: '',
    email: '',
    address: '',
    phone: '',
    availability: [0, 1, 2],
    appointments: [],
  },
  {
    id: '3',
    avatar: 'https://images2.imgbox.com/19/80/QQZwXNbP_o.png',
    title: Specialty.PEDIATRICS,
    name: '',
    specialty: [Specialty.NEUROLOGY],
    bio: '',
    email: '',
    address: '',
    phone: '',
    availability: [3, 4, 5],
    appointments: [],
  },
  {
    id: '4',
    avatar: 'https://images2.imgbox.com/4b/fe/k8H0shP2_o.png',
    title: Specialty.SURGERY,
    name: '',
    specialty: [Specialty.NEUROLOGY],
    bio: '',
    email: '',
    address: '',
    phone: '',
    availability: [6],
    appointments: [],
  },
  {
    id: '5',
    avatar: 'https://imgbox.com/k8H0shP2',
    title: Specialty.PSYCHIATRY,
    name: '',
    specialty: [Specialty.NEUROLOGY],
    bio: '',
    email: '',
    address: '',
    phone: '',
    availability: [0, 2],
    appointments: [],
  },
  {
    id: '6',
    avatar: 'https://imgbox.com/lRBBYcMj',
    title: Specialty.UROLOGY,
    name: '',
    specialty: [Specialty.NEUROLOGY],
    bio: '',
    email: '',
    address: '',
    phone: '',
    availability: [0, 1, 2, 3, 4, 5, 6],
    appointments: [],
  },
  {
    id: '7',
    avatar: 'https://imgbox.com/h79FIvf2',
    title: Specialty.PEDIATRICS,
    name: '',
    specialty: [Specialty.NEUROLOGY],
    bio: '',
    email: '',
    address: '',
    phone: '',
    availability: [5],
    appointments: [],
  },
];

export default list;
